#!/bin/bash

echo "🔧 Creating Android Studio Project with Gradle Build System..."

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Build web assets first
echo -e "${BLUE}Building web application...${NC}"
npm run build

# Create Android Studio project structure
ANDROID_PROJECT="zivora-android-studio"
echo -e "${BLUE}Creating Android Studio project structure...${NC}"
rm -rf $ANDROID_PROJECT
mkdir -p $ANDROID_PROJECT

# Create complete Android project directory structure
mkdir -p $ANDROID_PROJECT/app/src/main/{java/com/zivoramobile/zivora,res/{layout,values,drawable,mipmap-{mdpi,hdpi,xhdpi,xxhdpi,xxxhdpi}},assets}
mkdir -p $ANDROID_PROJECT/app/src/{debug,release}
mkdir -p $ANDROID_PROJECT/gradle/wrapper

# Copy web assets to Android assets directory
echo -e "${YELLOW}Copying web assets...${NC}"
cp -r dist/public/* $ANDROID_PROJECT/app/src/main/assets/

# Create root build.gradle (Project level)
cat > $ANDROID_PROJECT/build.gradle << 'EOF'
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
EOF

# Create app-level build.gradle
cat > $ANDROID_PROJECT/app/build.gradle << 'EOF'
plugins {
    id 'com.android.application'
}

android {
    namespace 'com.zivoramobile.zivora'
    compileSdk 34

    defaultConfig {
        applicationId "com.zivoramobile.zivora"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
        debug {
            minifyEnabled false
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt']
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
EOF

# Create settings.gradle
cat > $ANDROID_PROJECT/settings.gradle << 'EOF'
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Zivora"
include ':app'
EOF

# Create gradle.properties
cat > $ANDROID_PROJECT/gradle.properties << 'EOF'
# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
EOF

# Create local.properties (will be generated by Android Studio)
cat > $ANDROID_PROJECT/local.properties << 'EOF'
# Location of the Android SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
sdk.dir=/Users/username/Library/Android/sdk
EOF

# Create Gradle Wrapper files
cat > $ANDROID_PROJECT/gradle/wrapper/gradle-wrapper.properties << 'EOF'
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-bin.zip
networkTimeout=10000
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
EOF

# Create gradlew script
cat > $ANDROID_PROJECT/gradlew << 'EOF'
#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
##############################################################################

# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if [ "$darwin" = "true" ]; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
    
    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null`
    SEP=""
    for dir in $ROOTDIRSRAW ; do
        ROOTDIRS="$ROOTDIRS$SEP$dir"
        SEP="|"
    done
    OURCYGPATTERN="(^($ROOTDIRS))"
    # Add a user-defined pattern to the cygpath arguments
    if [ "$GRADLE_CYGPATTERN" != "" ] ; then
        OURCYGPATTERN="$OURCYGPATTERN|($GRADLE_CYGPATTERN)"
    fi
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    i=0
    for arg in "$@" ; do
        CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" -`
        CHECK2=`echo "$arg"|egrep -c "^-"`                                 ### Determine if an option

        if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then                    ### Added a condition
            eval `echo args$i`=`cygpath --path --ignore --mixed "$arg"`
        else
            eval `echo args$i`="\"$arg\""
        fi
        i=`expr $i + 1`
    done
    case $i in
        0) set -- ;;
        1) set -- "$args0" ;;
        2) set -- "$args0" "$args1" ;;
        3) set -- "$args0" "$args1" "$args2" ;;
        4) set -- "$args0" "$args1" "$args2" "$args3" ;;
        5) set -- "$args0" "$args1" "$args2" "$args3" "$args4" ;;
        6) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" ;;
        7) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" ;;
        8) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" ;;
        9) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" "$args8" ;;
    esac
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}
APP_ARGS=`save "$@"`

# Collect all arguments for the java command
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

exec "$JAVACMD" "$@"
EOF

chmod +x $ANDROID_PROJECT/gradlew

# Create gradlew.bat for Windows
cat > $ANDROID_PROJECT/gradlew.bat << 'EOF'
@rem
@rem Copyright 2015 the original author or authors.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License");
@rem you may not use this file except in compliance with the License.
@rem You may obtain a copy of the License at
@rem
@rem      https://www.apache.org/licenses/LICENSE-2.0
@rem
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS,
@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@rem See the License for the specific language governing permissions and
@rem limitations under the License.
@rem

@if "%DEBUG%" == "" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows
@rem
@rem ##########################################################################

@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%" == "" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Resolve any "." and ".." in APP_HOME to make it shorter.
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi

@rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"

@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if "%ERRORLEVEL%" == "0" goto execute

echo.
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto execute

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail

:execute
@rem Setup the command line

set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar


@rem Execute Gradle
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*

:end
@rem End local scope for the variables with windows NT shell
if "%ERRORLEVEL%"=="0" goto mainEnd

:fail
rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
rem the _cmd_ return code.
if not "" == "%GRADLE_EXIT_CONSOLE%" exit 1
exit /b 1

:mainEnd
if "%OS%"=="Windows_NT" endlocal

:omega
EOF

# Create proper AndroidManifest.xml
cat > $ANDROID_PROJECT/app/src/main/AndroidManifest.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

    <application
        android:allowBackup="true"
        android:dataExtractionRules="@xml/data_extraction_rules"
        android:fullBackupContent="@xml/backup_rules"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:theme="@style/Theme.Zivora"
        android:usesCleartextTraffic="true"
        tools:targetApi="31">

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:launchMode="singleTop"
            android:windowSoftInputMode="adjustResize">
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
EOF

# Create MainActivity.java
cat > $ANDROID_PROJECT/app/src/main/java/com/zivoramobile/zivora/MainActivity.java << 'EOF'
package com.zivoramobile.zivora;

import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.webkit.WebSettings;
import android.view.View;

public class MainActivity extends AppCompatActivity {
    private WebView webView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        webView = findViewById(R.id.webview);
        
        // Configure WebView settings
        WebSettings webSettings = webView.getSettings();
        webSettings.setJavaScriptEnabled(true);
        webSettings.setDomStorageEnabled(true);
        webSettings.setAllowFileAccess(true);
        webSettings.setAllowContentAccess(true);
        webSettings.setAllowFileAccessFromFileURLs(true);
        webSettings.setAllowUniversalAccessFromFileURLs(true);
        webSettings.setCacheMode(WebSettings.LOAD_DEFAULT);
        webSettings.setDatabaseEnabled(true);
        webSettings.setAppCacheEnabled(true);

        // Set WebView client to handle page navigation
        webView.setWebViewClient(new WebViewClient() {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                view.loadUrl(url);
                return true;
            }
        });

        // Load the main app
        webView.loadUrl("file:///android_asset/index.html");
    }

    @Override
    public void onBackPressed() {
        if (webView.canGoBack()) {
            webView.goBack();
        } else {
            super.onBackPressed();
        }
    }
}
EOF

# Create activity_main.xml layout
cat > $ANDROID_PROJECT/app/src/main/res/layout/activity_main.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <WebView
        android:id="@+id/webview"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</LinearLayout>
EOF

# Create strings.xml
cat > $ANDROID_PROJECT/app/src/main/res/values/strings.xml << 'EOF'
<resources>
    <string name="app_name">Zivora</string>
</resources>
EOF

# Create colors.xml
cat > $ANDROID_PROJECT/app/src/main/res/values/colors.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="purple_200">#FFBB86FC</color>
    <color name="purple_500">#FF6200EE</color>
    <color name="purple_700">#FF3700B3</color>
    <color name="teal_200">#FF03DAC5</color>
    <color name="teal_700">#FF018786</color>
    <color name="black">#FF000000</color>
    <color name="white">#FFFFFFFF</color>
    <color name="zivora_purple">#9333EA</color>
</resources>
EOF

# Create themes.xml
cat > $ANDROID_PROJECT/app/src/main/res/values/themes.xml << 'EOF'
<resources xmlns:tools="http://schemas.android.com/tools">
    <!-- Base application theme. -->
    <style name="Theme.Zivora" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Primary brand color. -->
        <item name="colorPrimary">@color/zivora_purple</item>
        <item name="colorPrimaryVariant">@color/purple_700</item>
        <item name="colorOnPrimary">@color/white</item>
        <!-- Secondary brand color. -->
        <item name="colorSecondary">@color/teal_200</item>
        <item name="colorSecondaryVariant">@color/teal_700</item>
        <item name="colorOnSecondary">@color/black</item>
        <!-- Status bar color. -->
        <item name="android:statusBarColor" tools:targetApi="l">?attr/colorPrimaryVariant</item>
        <!-- Customize your theme here. -->
    </style>
</resources>
EOF

# Create XML configuration files
mkdir -p $ANDROID_PROJECT/app/src/main/res/xml
cat > $ANDROID_PROJECT/app/src/main/res/xml/backup_rules.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
    <!-- Exclude sensitive data from backup -->
    <exclude domain="sharedpref" path="." />
    <exclude domain="database" path="." />
</full-backup-content>
EOF

cat > $ANDROID_PROJECT/app/src/main/res/xml/data_extraction_rules.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<data-extraction-rules>
    <cloud-backup>
        <exclude domain="sharedpref" path="." />
        <exclude domain="database" path="." />
    </cloud-backup>
    <device-transfer>
        <exclude domain="sharedpref" path="." />
        <exclude domain="database" path="." />
    </device-transfer>
</data-extraction-rules>
EOF

# Create app icons for all densities
echo -e "${YELLOW}Creating app icons for all densities...${NC}"
for density in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
    case $density in
        mdpi) size=48;;
        hdpi) size=72;;
        xhdpi) size=96;;
        xxhdpi) size=144;;
        xxxhdpi) size=192;;
    esac
    
    python3 << PYTHON_SCRIPT
import struct
import zlib

size = $size
density = "$density"

# Create launcher icon
with open(f'$ANDROID_PROJECT/app/src/main/res/mipmap-{density}/ic_launcher.png', 'wb') as f:
    # PNG signature
    f.write(b'\x89PNG\r\n\x1a\n')
    
    # IHDR chunk
    f.write(struct.pack('>I', 13))
    f.write(b'IHDR')
    f.write(struct.pack('>II', size, size))
    f.write(b'\x08\x06\x00\x00\x00')  # RGBA
    
    # CRC for IHDR
    ihdr_data = b'IHDR' + struct.pack('>II', size, size) + b'\x08\x06\x00\x00\x00'
    f.write(struct.pack('>I', zlib.crc32(ihdr_data) & 0xffffffff))
    
    # Create purple Zivora icon
    purple = b'\x99\x33\xCC\xFF'  # Purple with alpha
    row = b'\x00' + purple * size  # filter + pixels
    image_data = row * size
    compressed = zlib.compress(image_data)
    
    # IDAT chunk
    f.write(struct.pack('>I', len(compressed)))
    f.write(b'IDAT')
    f.write(compressed)
    f.write(struct.pack('>I', zlib.crc32(b'IDAT' + compressed) & 0xffffffff))
    
    # IEND chunk
    f.write(struct.pack('>I', 0))
    f.write(b'IEND')
    f.write(struct.pack('>I', 0xAE426082))

# Create round launcher icon
with open(f'$ANDROID_PROJECT/app/src/main/res/mipmap-{density}/ic_launcher_round.png', 'wb') as f:
    # PNG signature
    f.write(b'\x89PNG\r\n\x1a\n')
    
    # IHDR chunk
    f.write(struct.pack('>I', 13))
    f.write(b'IHDR')
    f.write(struct.pack('>II', size, size))
    f.write(b'\x08\x06\x00\x00\x00')
    
    # CRC for IHDR
    ihdr_data = b'IHDR' + struct.pack('>II', size, size) + b'\x08\x06\x00\x00\x00'
    f.write(struct.pack('>I', zlib.crc32(ihdr_data) & 0xffffffff))
    
    # Create round purple icon
    center = size // 2
    pixels = []
    for y in range(size):
        row_pixels = [b'\x00']  # filter
        for x in range(size):
            dist = ((x - center) ** 2 + (y - center) ** 2) ** 0.5
            if dist <= center - 2:  # Slightly smaller circle
                row_pixels.append(b'\x99\x33\xCC\xFF')  # Purple
            else:
                row_pixels.append(b'\x00\x00\x00\x00')  # Transparent
        pixels.append(b''.join(row_pixels))
    
    image_data = b''.join(pixels)
    compressed = zlib.compress(image_data)
    
    # IDAT chunk
    f.write(struct.pack('>I', len(compressed)))
    f.write(b'IDAT')
    f.write(compressed)
    f.write(struct.pack('>I', zlib.crc32(b'IDAT' + compressed) & 0xffffffff))
    
    # IEND chunk
    f.write(struct.pack('>I', 0))
    f.write(b'IEND')
    f.write(struct.pack('>I', 0xAE426082))

print(f"Icons created for {density}")
PYTHON_SCRIPT
done

# Create proguard-rules.pro
cat > $ANDROID_PROJECT/app/proguard-rules.pro << 'EOF'
# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile

# Keep WebView JavaScript interface
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

# Keep native methods
-keepclasseswithmembernames class * {
    native <methods>;
}
EOF

# Create .gitignore
cat > $ANDROID_PROJECT/.gitignore << 'EOF'
*.iml
.gradle
/local.properties
/.idea/caches
/.idea/libraries
/.idea/modules.xml
/.idea/workspace.xml
/.idea/navEditor.xml
/.idea/assetWizardSettings.xml
.DS_Store
/build
/captures
.externalNativeBuild
.cxx
local.properties
EOF

# Create comprehensive README with build instructions
cat > $ANDROID_PROJECT/README.md << 'EOF'
# Zivora Android Studio Project

This is a complete Android Studio project with Gradle build system for the Zivora migraine tracking app.

## Prerequisites

1. **Android Studio** (latest version recommended)
2. **Java JDK 8 or higher**
3. **Android SDK** (API level 24-34)

## Setup Instructions

### Option 1: Using Android Studio (Recommended)

1. **Open Project**:
   - Launch Android Studio
   - Click "Open an existing Android Studio project"
   - Navigate to this project folder and select it

2. **Sync Project**:
   - Android Studio will automatically sync Gradle files
   - Wait for the sync to complete

3. **Build APK**:
   - Go to `Build` menu > `Build Bundle(s) / APK(s)` > `Build APK(s)`
   - Or use `Build` menu > `Generate Signed Bundle / APK` for release

### Option 2: Using Command Line

1. **Navigate to project directory**:
   ```bash
   cd zivora-android-studio
   ```

2. **Build Debug APK**:
   ```bash
   ./gradlew assembleDebug
   ```

3. **Build Release APK**:
   ```bash
   ./gradlew assembleRelease
   ```

## APK Output Locations

- **Debug APK**: `app/build/outputs/apk/debug/app-debug.apk`
- **Release APK**: `app/build/outputs/apk/release/app-release.apk`

## Project Structure

```
zivora-android-studio/
├── app/
│   ├── src/main/
│   │   ├── java/com/zivoramobile/zivora/
│   │   │   └── MainActivity.java
│   │   ├── res/
│   │   │   ├── layout/activity_main.xml
│   │   │   ├── values/strings.xml
│   │   │   ├── values/colors.xml
│   │   │   ├── values/themes.xml
│   │   │   └── mipmap-*/ic_launcher*.png
│   │   ├── assets/
│   │   │   └── [Web app files]
│   │   └── AndroidManifest.xml
│   ├── build.gradle
│   └── proguard-rules.pro
├── gradle/wrapper/
├── build.gradle
├── settings.gradle
├── gradle.properties
└── gradlew / gradlew.bat
```

## Features

- **WebView-based app** loading Zivora web application
- **Proper Android project structure** with all required files
- **Multi-density app icons** (mdpi to xxxhdpi)
- **Material Design theming** with Zivora purple branding
- **Gradle build system** with both debug and release configurations
- **ProGuard configuration** for code optimization

## Troubleshooting

1. **Gradle sync failed**: 
   - Check internet connection
   - Update Android Studio and SDK tools

2. **Build errors**:
   - Clean and rebuild: `Build` > `Clean Project`, then `Build` > `Rebuild Project`
   - Or command line: `./gradlew clean build`

3. **SDK not found**:
   - Update `local.properties` with correct SDK path
   - Or let Android Studio auto-configure it

## APK Installation

The generated APKs can be installed on Android devices by:
1. Enabling "Install unknown apps" in device settings
2. Transferring APK to device and opening it
3. Following installation prompts

The APKs generated by this Android Studio project will have proper signatures and should install without parsing errors.
EOF

# Package the Android Studio project
echo -e "${BLUE}Creating Android Studio project package...${NC}"
cd $ANDROID_PROJECT
zip -r ../dist/public/zivora-android-studio.zip . -x "*.git*" "build/*" ".gradle/*"
cd ..

# Clean up
rm -rf $ANDROID_PROJECT

echo ""
echo -e "${GREEN}✅ Android Studio project created successfully!${NC}"
echo ""
ls -lh dist/public/zivora-android-studio.zip

# Get domain
DOMAIN=$(echo $REPLIT_DEV_DOMAIN || echo "localhost:5000")
if [ -z "$DOMAIN" ] || [ "$DOMAIN" = "localhost:5000" ]; then
    DOMAIN="3ee4d6a9-e442-4a38-b9d4-69a8bb496f55-00-2spibzzix19bx.janeway.replit.dev"
fi

echo ""
echo -e "${YELLOW}📥 Download Android Studio Project:${NC}"
echo "https://$DOMAIN/zivora-android-studio.zip"
echo ""
echo -e "${GREEN}📋 Instructions:${NC}"
echo "1. Download and extract the zip file"
echo "2. Open the project in Android Studio"
echo "3. Let Gradle sync complete"
echo "4. Build > Build Bundle(s) / APK(s) > Build APK(s)"
echo "5. APK will be in app/build/outputs/apk/"
echo ""
echo -e "${BLUE}This creates a proper Android Studio project with Gradle that generates installable APKs${NC}"