name: Android APK

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install platform/build-tools
        run: |
          yes | sdkmanager --licenses > /dev/null
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Make Gradle wrapper executable
        run: chmod +x android/gradlew

      - name: Generate debug keystore for CI
        run: |
          mkdir -p ~/.android
          keytool -genkeypair -v \
            -storetype PKCS12 \
            -keystore ~/.android/debug.keystore \
            -storepass android \
            -keypass android \
            -dname "CN=Android Debug,O=Android,C=US" \
            -alias androiddebugkey \
            -keyalg RSA -keysize 2048 -validity 10000


      - name: Build Release APK (verbose)
        working-directory: android
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx3g -Dorg.gradle.daemon=false"
        run: ./gradlew --version && ./gradlew clean assembleRelease --stacktrace --info --warning-mode all

      - name: List build outputs (debug)
        if: always()
        run: |
          echo "Outputs under android/app/build/outputs:"
          ls -R android/app/build/outputs || true

      - name: Upload APK (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: android/app/build/outputs/apk/release/*.apk

      - name: Upload Gradle problems report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-problems-report
          path: android/build/reports/problems/**/*
