name: Android APK

on:
  workflow_dispatch: {}   # Run manually
  push:
    branches: [ main ]    # Optional: auto-run on each push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install build-tools
        run: |
          yes | sdkmanager --licenses > /dev/null
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build Release APK
        working-directory: android
        run: ./gradlew clean assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: android/app/build/outputs/apk/release/*.apk
